name: CI

on:
  release:
    types: [ released ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/halon176/h-crypto-price-bot:latest
      - name: Publish the Docker image
        run: docker push ghcr.io/halon176/h-crypto-price-bot:latest